version: "3"

services:
  chore_champs_client:
    container_name: chore_champs_client
    build:
      context: ../client
    env_file:
      - .env
    restart: unless-stopped

  chore_champs_api:
    container_name: chore_champs_api
    build:
      context: ../api
    environment:
      - TZ=America/Denver
    restart: unless-stopped

  chore_champs_db:
    image: postgres
    container_name: chore_champs_db
    environment:
      - POSTGRES_DB=ChoreChamps
      - POSTGRES_USER=ChoreChampsUser
      - POSTGRES_PASSWORD=asdvoinsadvpoasndasvoi
      - TZ=America/Denver
    restart: unless-stopped
    volumes:
      - ../api/schema.sql:/docker-entrypoint-initdb.d/schema.sql

  chore_champs_swag:
    image: lscr.io/linuxserver/swag
    container_name: chore_champs_swag
    cap_add:
      - NET_ADMIN
    env_file:
      - .env
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Denver
      - URL=chorechamps.duckdns.org
      - VALIDATION=duckdns
      - STAGING=false
    volumes:
      - /home/bridger/data/chorechampswag:/config
      - ../client/swagdefault.conf:/config/nginx/site-confs/default.conf
    ports:
      - 0.0.0.0:5003:80
    restart: unless-stopped

volumes:
  developer_home:
