version: "3"

services:
  chore_champs_client:
    container_name: chore_champs_client
    build:
      context: .
    user: developer
    volumes:
      - ../:/app/:z
    env_file:
      - .env
    restart: unless-stopped
    command: >
      sh -c "
        cd client
        npm i
        npm run dev
      "

  chore_champs_api:
    container_name: chore_champs_api
    build:
      context: .
    user: root
    volumes:
      - ../:/app/
      - developer_home:/home/developer
    working_dir: /app
    environment:
      - TZ=America/Denver
    restart: unless-stopped
    command: >
      sh -c "
        mkdir -p /home/developer/virtualenv
        mkdir /other_api
        chown -R developer:developer /home/developer/virtualenv
        chown -R developer:developer /other_api
        su - developer
        cp -r api /other_api

        cd /other_api
        source /home/developer/.virtualenvs/choreChamps/bin/activate
        pip install -r requirements.txt
        uvicorn src.main:app --host 0.0.0.0 --reload --port 3000
      "

  chore_champs_db:
    image: postgres
    container_name: chore_champs_db
    environment:
      - POSTGRES_DB=ChoreChamps
      - POSTGRES_USER=ChoreChampsUser
      - POSTGRES_PASSWORD=asdvoinsadvpoasndasvoi
      - TZ=America/Denver
    restart: unless-stopped
    volumes:
      - ../api/schema.sql:/docker-entrypoint-initdb.d/schema.sql

  chore_champs_swag:
    image: lscr.io/linuxserver/swag
    container_name: chore_champs_swag
    cap_add:
      - NET_ADMIN
    env_file:
      - .env
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Denver
      - URL=chorechamps.duckdns.org
      - VALIDATION=duckdns
      - STAGING=true
    volumes:
      - /home/bridger/data/chorechampswag:/config
      - ../client/swagdefault.conf:/config/nginx/site-confs/default.conf
    ports:
      - 0.0.0.0:5003:80
    restart: unless-stopped

volumes:
  developer_home:
